### ISSUE TITLE
What are the nodes that the KF horizon servers trust?

### ISSUE THREAD

**Issue by TheBubblePopped** [kinecosystem/blockchain-ops#202]
Since the relation is transitive it would be not bad to know how the config file of you guys looks like.

**Comment by hitwill** [comment]
You can see the configuration file in [this post](https://medium.com/kinblog/how-to-run-a-node-on-the-kin-blockchain-9dfcbbfda891) on Medium:

**Comment by TheBubblePopped** [comment]
First of all, thank you for sharing. I have read that article. Second, Known_peers are set to the kin foundation and the kik foundation. 

That's a centralized configuration. If everyone implements that we ll never reach consensus  if they disappear. 
I also doubt that ( could be wrong ofc) the Kin Foundation itself is using that config. I mean you wouldn't put yourself as a peer would you?

I'll read some stuff today and if i find something relevant i'll give an update.I think i can not fully express my though due to the lack of experience / knowledge.

**Comment by hitwill** [comment]
Yeah, I ran a node about a month or two ago - after hooking it up to the network, my node discovered a bunch of others. (I can't remember if it was 30 something nodes, or more). But it definitely reached out and found others, after starting off with the configuration file.

I just set it up in ephemeral mode, and could use postgre to view the database that stores the node locations. Thing is, there are no node "human readable names". Just ip and blockchain addresses.

**Comment by TheBubblePopped** [comment]
That's strange. I see as expected 3 authenticated_peers and a quorum set of 8. (The quorum set is kin,kik and their subnodes from the config file)

The config file mentioned in the article you shared is also a bit different from the preconfigured docker file. Target_peer_connections=8.

Did you set this to 30?
If yes then there is still a problem with centralization. From what i understand when you start the kin-core(stellar_core) since you have no preferred peers it will try to make connections with known nodes in the DB aka the known_peers. If you have 30 and your known_peers has a cardinality of 8 then it will ask these 8 validators to give you more nodes they have under their "known peers".

**Comment by TheBubblePopped** [comment]
Oh and here is something else i noticed:

I am getting a fail_with and kin is [referenced](https://i.imgur.com/Rvp5Jfa.png) (They r authenticated tho)

**Comment by TheBubblePopped** [comment]
found the info i need in the db
