### ISSUE TITLE
Missing known coursors in the config file

### ISSUE THREAD

**Issue by TheBubblePopped** [kinecosystem/blockchain-ops#204]
Is this intentional?
file is located at blockchain-ops/apps/docker-quickstart/pubnet/core/etc/stellar-core.cfg

Missing cursors

stellar-core uses “cursors” to ensure that garbage collection doesn’t delete data needed by consumers.

If cursors have not been configured, what can happen is that before Horizon has a chance to set a cursor, stellar-core’s garbage collection can run and delete some data that Horizon expects.

Solution is to properly define cursors in stellar-core’s configuration:

KNOWN_CURSORS=["HORIZON"]

**Comment by oryband** [comment]
hey @TheBubblePopped ! thanks for the issue. `"HORIZON"` is a default cursor and is generated automatically and used by Horizon in the quickstart app.

Lemme know if that answers your question.

**Comment by TheBubblePopped** [comment]
Oh i see, ty. 
I think you answered my question but give me just 1 more week to trippleconfirm that i fully understand how it works.I ll close the ticket by myself afterwards.
